logging:
  level:
    org:
      springframework: INFO


################### DataSource Configuration ##########################
spring:
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demop7?createDatabaseIfNotExist=true
    username: root
    password: admin1

  ################### Hibernate Configuration ##########################
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem