logging:
  level:
    org:
      springframework: INFO


################### DataSource Configuration ##########################
spring:
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testp7?createDatabaseIfNotExist=true
    username: root
    password: admin1

    initialize: true

  ################### Hibernate Configuration ##########################

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true